### ISSUE TITLE
Could `CODer.py` suitable for `MAGIC_RNA` data?

### ISSUE THREAD

**Issue by jiangpuxuan** [diogomribeiro/sc_cop#1]
Hi Ribeiro!
I am using sc_cop for single-cell transcriptome analysis.
I wonder if it is suitable to use `CODer.py`  on magicked matrix.

Thank you for your help!

**Comment by diogomribeiro** [comment]
Hi, CODer.py is not specific for single cell data. Input is a custom BED file where rows are genes and columns are samples, also uses a few initial columns described here:
#chr    start   end     gene    info    strand  sample1  sample2

Cheers,
Diogo
