### ISSUE TITLE
`CODer.py` consumed more than 180g VIRT.

### ISSUE THREAD

**Issue by jiangpuxuan** [diogomribeiro/sc_cop#4]
Here is my code:
```
python3 ~/packages/sc_cop-main/CODer.py expression_matrix.bed ./output/ 1000 --fdrCutoff 0.01
#My `CODer.py expression_matrix.bed` has 5000 sample
```
It consumed more than 180g VIRT so my server cannot run it.

How could I reduce the VIRT cosume? Thank you for your help!

**Comment by diogomribeiro** [comment]
Yes, I forgot to mention, there is a  --lowMem 1 flag you can use. Jobs take a bit longer to run though. It has to do with how the randomisation matrices are stored, which is the heavy bit.
Hope this helps,
Diogo

**Comment by jiangpuxuan** [comment]
> Yes, I forgot to mention, there is a --lowMem 1 flag you can use. Jobs take a bit longer to run though. It has to do with how the randomisation matrices are stored, which is the heavy bit. Hope this helps, Diogo

Thank you, that worked.
