### ISSUE TITLE
Could `ShareSeqCoex.py` work in `non`-Share-seq method ?

### ISSUE THREAD

**Issue by jiangpuxuan** [diogomribeiro/sc_cop#5]
We truly appreciate your help and `CODer.py` script, for it discovering many unprecedented features of our data!

I have both an `scRNA-seq` and `scATAC-seq` data for one same kind of biological sample.
Differing from `Share-seq`, cells in my bi-omics data cannot correspond.
Could I use `ShareSeqCoex.py` in my data?
Thank you for your help!

**Comment by diogomribeiro** [comment]
Thank you. ShareSeqCoex.py matches scRNA-seq and scATAC-seq on the same cells, given by a tag (barcode). If no correspondance is given, it will not work. I think there are several methods available to match scRNA-seq and scATAC-seq profiles from different cell pools.
Cheers,
Diogo

**Comment by jiangpuxuan** [comment]
> 

Thank you for your advice!
